/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterPatientRouteImport } from './routes/register-patient'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPatientRoute = RegisterPatientRouteImport.update({
  id: '/register-patient',
  path: '/register-patient',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/register-patient': typeof RegisterPatientRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/register-patient': typeof RegisterPatientRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/register-patient': typeof RegisterPatientRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/login'
    | '/patients'
    | '/register-patient'
    | '/settings'
    | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/login'
    | '/patients'
    | '/register-patient'
    | '/settings'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/dashboard'
    | '/login'
    | '/patients'
    | '/register-patient'
    | '/settings'
    | '/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PatientsRoute: typeof PatientsRoute
  RegisterPatientRoute: typeof RegisterPatientRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-patient': {
      id: '/register-patient'
      path: '/register-patient'
      fullPath: '/register-patient'
      preLoaderRoute: typeof RegisterPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PatientsRoute: PatientsRoute,
  RegisterPatientRoute: RegisterPatientRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
